{{- if .Values.backendConfig.enabled -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "controlPlane.fullname" . }}
spec:
  iap:
    enabled: {{ .Values.backendConfig.iap.enabled }}
    oauthclientCredentials:
      secretName: {{ .Values.backendConfig.iap.secretName }}
{{- end }}

{{ if .Values.monitoring.backendConfig.enabled -}}
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "controlPlane.fullname" . }}-grafana
spec:
  iap:
    enabled: {{ .Values.monitoring.backendConfig.iap.enabled }}
    oauthclientCredentials:
      secretName: {{ .Values.monitoring.backendConfig.iap.secretName }}
{{- end }}
